language: node_js
node_js: stable
branches:
  only:
  - master
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
before_install:
- git config --global user.name "johnpoint"
- git config --global user.email "me@lvcshu.com"
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- npm install -g hexo-cli
install:
- yarn
script:
- git clone https://github.com/hexo-theme-XvA/hexo-theme-XvA.github.io ~/hexo-theme-XvA.github.io && cd ~/hexo-theme-XvA.github.io && git checkout source
- git clone https://github.com/johnpoint/hexo-theme-XvA ~/hexo-theme-XvA.github.io/themes/XvA
- cp ~/hexo-theme-XvA.github.io/themes/_config.yml ~/hexo-theme-XvA.github.io/themes/XvA/
- cd ~/hexo-theme-XvA.github.io && mkdir hexo && cd ~/hexo-theme-XvA.github.io/hexo && hexo init ~/hexo-theme-XvA.github.io/hexo && rm ~/hexo-theme-XvA.github.io/hexo/_config.yml ~/hexo-theme-XvA.github.io/hexo/source ~/hexo-theme-XvA.github.io/hexo/themes -rf
- cp ~/hexo-theme-XvA.github.io/source ~/hexo-theme-XvA.github.io/hexo -r && cp ~/hexo-theme-XvA.github.io/themes ~/hexo-theme-XvA.github.io/hexo -r && cp ~/hexo-theme-XvA.github.io/_config.yml ~/hexo-theme-XvA.github.io/hexo
- cd ~/hexo-theme-XvA.github.io/hexo && npm install hexo-generator-feed --save
- cd ~/hexo-theme-XvA.github.io/hexo && hexo g
after_success:
- mkdir ~/hexo-theme-XvA.github.io/hexo/push && cd ~/hexo-theme-XvA.github.io/hexo/push
- git clone https://github.com/hexo-theme-XvA/hexo-theme-XvA.github.io ~/hexo-theme-XvA.github.io/hexo/push && cd ~/hexo-theme-XvA.github.io/hexo/push && git checkout master
- cd ~/hexo-theme-XvA.github.io/hexo/push && rm * -rf && cp ../public/* . -r
- cd ~/hexo-theme-XvA.github.io/hexo/push && git add --all . && git commit -m "Travis CI Auto Build" && git push --quiet https://$REPO_TOKEN@github.com/hexo-theme-XvA/hexo-theme-XvA.github.io master