language: node_js
node_js: stable
branches:
  only:
  - master
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
before_install:
- git config --global user.name "johnpoint"
- git config --global user.email "me@lvcshu.com"
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- npm install -g hexo-cli
install:
- yarn
script:
- git clone https://github.com/hexo-theme-XvA/hexo-theme-XvA.github.io && cd hexo-theme-XvA.github.io && git checkout source
- cd theme/ && git clone https://github.com/johnpoint/hexo-theme-XvA XvA
- cp _config.yml XvA/
- cd ../ && mkdir hexo && cd hexo && hexo init . && rm _config.yml source themes -rf
- cp ../source . -r && cp ../themes . -r && cp ../_config.yml .
- npm install hexo-generator-feed --save
- hexo g
after_success:
- mkdir push && cd push
- git clone https://github.com/hexo-theme-XvA/hexo-theme-XvA.github.io . && git checkout master
- rm * -rf && cp ../public/* . -r
- git add --all .
- git commit -m "Travis CI Auto Build"
- git push --quiet https://$REPO_TOKEN@github.com/hexo-theme-XvA/hexo-theme-XvA.github.io master