language: node_js
node_js: stable
branches:
  only:
  - master
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
before_install:
- git config --global user.name "johnpoint"
- git config --global user.email "me@lvcshu.com"
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- npm install -g hexo-cli
install:
- yarn
script:
- mkdir test && cd test
- git clone https://github.com/hexo-theme-XvA/hexo-theme-XvA.github.io . && git checkout source
- cd ../ && mkdir build && cd build
- hexo init .
- cd themes && git clone https://github.com/johnpoint/hexo-theme-XvA XvA
- cd ../
- rm build/source/* && cp source/source/* build/source/ -p
- cp source/_config.yml && cp source/theme/_config.yml build/themes/XvA && cp source/theme/zh-Cu.yml build/themes/XvA/languages
- cd build/ && npm install hexo-generator-feed --save && hexo g
after_success:
- mkdir push && cd push
- git clone https://github.com/hexo-theme-XvA/hexo-theme-XvA.github.io . && git checkout master
- rm * -rf && cp ../public/* . -r
- git add --all . && git commit -m "Travis CI Auto Build"
- git push --quiet https://$REPO_TOKEN@github.com/hexo-theme-XvA/hexo-theme-XvA.github.io master