language: node_js
node_js: stable
branches:
  only:
  - master
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
before_install:
- git config --global user.name "johnpoint"
- git config --global user.email "me@lvcshu.com"
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- npm install -g hexo-cli
install:
- yarn
script:
- git clone https://github.com/hexo-theme-XvA/hexo-theme-XvA.github.io && cd hexo-theme-XvA.github.io && git checkout source
- git clone https://github.com/johnpoint/hexo-theme-XvA themes/XvA
- cp themes/_config.yml themes/XvA
- cp themes/zh-Cu.yml themes/XvA/languages
- npm install hexo-generator-feed --save
- hexo clean
- hexo g
- cd ../
- mkdir push/
- cd push/
- git clone https://github.com/hexo-theme-XvA/hexo-theme-XvA.github.io .
- rm * -rf
- cp ../public/* . -r
- git add --all .
- git commit -m "Travis CI Auto Build"
- git push --quiet https://$REPO_TOKEN@github.com/hexo-theme-XvA/hexo-theme-XvA.github.io master
