menu:
  Home: /
  Archives: /archives

post_copyright:
  enable: false
  author: 
  copyright_text: 本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">知识共享署名-相同方式共享 4.0 国际许可协议</a>进行许可。

widget:
  tag:
    enable: false
    count: 10
  friends:
    enable: false

friends:
  list:
    - title: 
      img:
      url:
      desc: 
      sidebar: false
      page: false

comment:
  disqus:
    enable: false
    shortname: 
    lazyload: false

analytics:
  google:
    enable: false
    id: 